
name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: make build

    - name: Format
      run: make fmt

    - name: Test
      run: make test

    - name: Install go-junit-report
      run: go install github.com/jstemmer/go-junit-report@latest

    - name: Run tests and generate report
      run: make test-report

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      with:
        files: ./test-results.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
